baseURL: https://adrian-patterson.github.io/
languageCode: en-us
title: Adrian Patterson
theme: ["PaperMod"]
mainsections: ["posts"]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - JSON

pagination:
  disableAliases: false
  pagerSize: 5

params:
  profileMode:
    enabled: true
    title: "Welcome!"
    subtitle: "So glad you're here."
    imageUrl: "/images/profile.jpg"
    imageTitle: "Adrian Patterson"
    imageWidth: 300
    imageHeight: 300
    buttons:
      - name: Posts
        url: "/posts"
      - name: Categories
        url: "/categories"
      - name: Tags
        url: "/tags"
      - name: Resume
        url: "/downloads/resume.pdf"
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true

  socialIcons:
    - name: "Github"
      url: "https://github.com/adrian-patterson"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/adrian-n-patterson/"
    - name: "Instagram"
      url: "https://adrian-snaps.github.io/"
    - name: "Email"
      url: "mailto:patterson.n.adrian@gmail.com"

menu:
  main:
    - name: Search 🔎
      url: search/
      weight: 4
    - name: Tags
      url: tags/
      weight: 3
    - name: Categories
      url: categories/
      weight: 2
    - name: Posts
      url: posts/
      weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false